const constants = {
  GET_TOTAL_QUESTIONS_AMOUNT: "GET_TOTAL_QUESTIONS_AMOUNT",
  CREATE_LOBBY: "CREATE_LOBBY",
  CONNECT_TO_LOBBY: "CONNECT_TO_LOBBY",
  GET_LEADERS: "GET_LEADERS",
  UPDATE_LOBBY: "UPDATE_LOBBY",
  SET_CURRENT_QUESTION_ANSWERED: "SET_CURRENT_QUESTION_ANSWERED",
  SET_CURRENT_PLAYER: "SET_CURRENT_PLAYER",
  SET_PRESSED_ANSWER: "SET_PRESSED_ANSWER"
};

export default constants;
