const constants = {
    GET_TOTAL_QUESTIONS_AMOUNT: "GET_TOTAL_QUESTIONS_AMOUNT",
    CREATE_LOBBY: "CREATE_LOBBY",
    CONNECT_TO_LOBBY: "CONNECT_TO_LOBBY",
    GET_WINNERS: "GET_WINNERS",
    UPDATE_LOBBY: "UPDATE_LOBBY"
};

export default constants;