const constants = {
    GET_TOTAL_QUESTIONS_AMOUNT: "GET_TOTAL_QUESTIONS_AMOUNT",
    GET_CURRENT_LOBBY: "GET_CURRENT_LOBBY",
    CREATE_LOBBY: "CREATE_LOBBY",
    GET_WINNERS: "GET_WINNERS"
};

export default constants;